---
- name: Launch new instance
  ec2:
    key_name: "{{ ec2_keypair }}"
    group_id: "{{ec2_security_grp }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    region: "{{ ec2_region }}"
    instance_tags: '{"Name":"{{ec2_tag_Name}}","Type":"{{ec2_tag_Type}}","Environment":"{{ec2_tag_Environment}}"}'
    wait: true
    count: "{{count}}"
    volumes:
      - device_name: /dev/sda1
        device_type: gp2
        volume_size: "{{ ec2_volume_size }}"
        delete_on_termination: true
  register: ec2
- debug: var=ec2
- name: Add new instances to host group
  add_host:
    name: "{{ item.public_ip }}"
    groups: "{{ host_group }}"
  with_items: "{{ ec2.instances }}"
- name: Wait for instance to boot
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    delay: 30
    timeout: 300
    state: started
  with_items: "{{ ec2.instances }}"
