---
- name: install apache2
  apt:
    name: apache2
    state: latest
    update_cache: yes
- name: Add index.html to the host web server
  copy:
     src: ./apache_files/index.html
     dest: /var/www/index.html
  notify:
    - start apache2
- name: Set ownership of index.html
  file:
    path: /var/www/index.html
    owner: www-data
    group: www-data
